### ISSUE TITLE
Small import issue

### ISSUE THREAD

**Issue by attibalazs** [petroGG/Basic-Well-Log-Interpretation#2]
Hi Mihai,

Thanks for a great repo 👍 I am working my way through it.

I just wanted to point out a few small issues:

data=data.replace('-999.00000',np.nan) is not correct and doesn't work it should be
data=data.replace(-999.00000,np.nan) because the values get imported as numbers you can check this by running data.dtypes

Also I'm not sure why you are specifying the index at the import because then the later rename lines don't make sense. I would do it like this:

data=pd.read_table('WA1.txt', delim_whitespace=True)
data=data.replace(-999.00000,np.nan)
data=data.rename(columns=({'M__DEPTH':'DEPT'}))

I would leave it at this since i prefer using the default index, but if you really want then you can set the index to be the DEPT column.

data.set_index('DEPT')

hope this makes sense, thanks again

**Comment by Philliec459** [comment]
Hi Mihai,

You might not be following this any more, but I really like what you have done with this repository on log analysis. This provides a great foundation to build upon. Thanks.

I am not sure how I should proceed with your program. I have downloaded your code and have been making my own modifications. As an example, I had some issues with the clay points shown on a graph. I have samples some of the most gumbo shales and the max clay content via XRD was about 65%. In my opinion we do not have the data on a plot to accurately pick a clay point. Therefore, I have changed all of the Vcl terms to Vshale. Shale points can usually be found on a xplot.

I have been making other mods to my version and am working on a Neutron-Density chart book solution to porosity and adding Dual Water saturations. Years ago I worked with George Coates on his newest Dual Water saturation program that he was using in his Mirian NMR analysis while at Numar. I found it to be a very simple method to employ in shaley sands. 

I guess the point of all of this is to ask you for permission to use your program as a foundation to what I am doing giving you full credit for your work. I am not sure how to proceed.

**Comment by petroGG** [comment]
Hi Craig,
I am also happy to know other professionals like you and increase my professional network and I hope one day to meet each other.

Unfortunately I was busy in the last time with personal/professional issues so I had no time to develop my personal G&G projects on github and android market. For the moment I dont think I will update any of my github work until the spring/summer of 2020.
The license for the code is: "do what do you what to do with the code if you consider it useful", so if you make modifications and improvements you are welcome.
Best Regards, Merry Christmas and Happy New Year,Mihai.


Sent from Yahoo Mail on Android 
 
  On Fri, 20 Dec 2019 at 19:38, Craig Phillips<notifications@github.com> wrote:   
Hi Mihai,

You might not be following this any more, but I really like what you have done with this repository on log analysis. This provides a great foundation to build upon. Thanks.

I am not sure how I should proceed with your program. I have downloaded your code and have been making my own modifications. As an example, I had some issues with the clay points shown on a graph. I have samples some of the most gumbo shales and the max clay content via XRD was about 65%. In my opinion we do not have the data on a plot to accurately pick a clay point. Therefore, I have changed all of the Vcl terms to Vshale. Shale points can usually be found on a xplot.

I have been making other mods to my version and am working on a Neutron-Density chart book solution to porosity and adding Dual Water saturations. Years ago I worked with George Coates on his newest Dual Water saturation program that he was using in his Mirian NMR analysis while at Numar. I found it to be a very simple method to employ in shaley sands.

I guess the point of all of this is to ask you for permission to use your program as a foundation to what I am doing giving you full credit for your work. I am not sure how to proceed.

**Comment by Philliec459** [comment]
Hi Mihai,


What a pleasant surprise to get you email. Merry Christmas to you.

I will be adding the KNN Neutron-Density chart-book solution to porosity this week after a few more tweaks. I originally only digitized in the Matrix Density-Porosity spine and rib plots for the Schlumberger CNL and TNPH tools at Fluid Densities of 1.0 and 1.1 (1.9 for TNPH), but there was not not enough points from the published charts. Therefore, I have now using a Neutron-Bulk Density matrix with pure chart-book results. This will be finished this week. The Neutron-Density porosity solution will be one of my repositories.

What I would like to do next is somehow take a branch off our your repository so that it will be intuitive that that your code is coming from you, and then I would add my modes. If you are in approval of what I have done, then maybe we can somehow show this to be collaboration. I have 40 years of Petrophysical experience, but just a few months with GigHub. I have a lot to learn on using GitHub, Python coding and collaborating with people like yourself so that I never tread on anyones toes. 

Mihai, I am impressed with your programming skills in combination with Petrophysics. What is your background? Nice work.

Happy Holidays and please have a Happy New Year. 


Best Regards, 
 
_______________________________
 
E. Craig Phillips
Petrophysicist, CBPC
 









459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
craig@cbpetro.com
www.cbpetro.com
 
The information contained in this electronic message is confidential, it constitutes a profesional and/or industrial secret in terms of the current legislation, and is intended for its recipient only. If you receive this message by mistake or if you are not the recipient thereof, please notify the sender and destroy it.

La informacion contenida en este mensaje de datos es confidencial, constituye un secreto industrial y/o profesional en terminos de la legislacion vigente y se encuentra dirigida exclusivamente al destinatario indicado en dicho mensaje. Si usted recibe esta informacion por error o si usted no es el destinatario del mensaje, favor de notificar al emisor, y destruyalo.



On Dec 25, 2019, at 1:30 AM, Mihai <notifications@github.com> wrote:

Hi Craig,
I am also happy to know other professionals like you and increase my professional network and I hope one day to meet each other.

Unfortunately I was busy in the last time with personal/professional issues so I had no time to develop my personal G&G projects on github and android market. For the moment I dont think I will update any of my github work until the spring/summer of 2020.
The license for the code is: "do what do you what to do with the code if you consider it useful", so if you make modifications and improvements you are welcome.
Best Regards, Merry Christmas and Happy New Year,Mihai.


Sent from Yahoo Mail on Android 

On Fri, 20 Dec 2019 at 19:38, Craig Phillips<notifications@github.com> wrote: 
Hi Mihai,

You might not be following this any more, but I really like what you have done with this repository on log analysis. This provides a great foundation to build upon. Thanks.

I am not sure how I should proceed with your program. I have downloaded your code and have been making my own modifications. As an example, I had some issues with the clay points shown on a graph. I have samples some of the most gumbo shales and the max clay content via XRD was about 65%. In my opinion we do not have the data on a plot to accurately pick a clay point. Therefore, I have changed all of the Vcl terms to Vshale. Shale points can usually be found on a xplot.

I have been making other mods to my version and am working on a Neutron-Density chart book solution to porosity and adding Dual Water saturations. Years ago I worked with George Coates on his newest Dual Water saturation program that he was using in his Mirian NMR analysis while at Numar. I found it to be a very simple method to employ in shaley sands.

I guess the point of all of this is to ask you for permission to use your program as a foundation to what I am doing giving you full credit for your work. I am not sure how to proceed.
